name: test_doodle
description: "Doodle transaction manager app"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  mockito: ^5.6.3

flutter:
  uses-material-design: true
